import type { Evaluation, MarketSnapshot } from "@/lib/types";

const verdictLabel = (value: Evaluation["verdict"]) => value === "NO_GO" ? "NO-GO" : value;

export function PrintReport({ evaluation, snapshot }: { evaluation: Evaluation; snapshot: MarketSnapshot }) {
  return <main className="print-report">
    <header className="print-cover"><div className="print-brand"><span>D</span><div><strong>DAWSEN AI</strong><small>PRODUCT INTELLIGENCE</small></div></div><p>爆款潜力评估报告<br/><span>PRODUCT POTENTIAL ASSESSMENT</span></p><div className="print-product"><div><small>{evaluation.product.brand || "UNBRANDED"} · {snapshot.policy.nameZh} / {snapshot.policy.nameEn}</small><h1>{evaluation.product.name}</h1><p>{evaluation.product.puffs.toLocaleString()} puffs · {evaluation.product.eLiquidMl} ml · {evaluation.product.nicotineMgMl} mg/ml</p></div><div className={`print-score ${evaluation.verdict.toLowerCase()}`}><strong>{evaluation.score}</strong><span>/100</span><small>{verdictLabel(evaluation.verdict)}</small></div></div><div className="print-meta"><span>Confidence / 置信度 <strong>{evaluation.confidence}%</strong></span><span>Completeness / 完整度 <strong>{evaluation.completeness}%</strong></span><span>Compliance / 合规 <strong>{evaluation.compliancePass ? "PASS" : "BLOCKED"}</strong></span></div></header>
    <section className="print-notice">本报告基于固定数据快照，仅用于产品决策支持，不构成销量、利润或市场准入保证。<br/>This report uses a fixed data snapshot for decision support only and does not guarantee sales, profit or market access.</section>
    {evaluation.hardFails.length > 0 && <section className="print-section blocker"><h2>市场准入阻断项 / Market-entry blockers</h2>{evaluation.hardFails.map((item) => <p key={item}>• {item}</p>)}</section>}
    <section className="print-section"><h2>六维评分 / Six-dimension profile</h2><div className="print-dimensions">{evaluation.dimensions.map((item) => <div key={item.key}><p><strong>{item.labelZh}</strong><span>{item.labelEn}</span><b>{item.score}</b></p><i><span style={{width:`${item.score}%`}}/></i><small>{item.rationaleZh}<br/>{item.rationaleEn}</small></div>)}</div></section>
    <section className="print-columns"><div className="print-section"><h2>市场法规 / Regulation</h2><p>{snapshot.policy.summaryZh}</p><p>{snapshot.policy.summaryEn}</p><dl><div><dt>尼古丁 / Nicotine</dt><dd>{snapshot.policy.maxNicotineMgMl} mg/ml</dd></div><div><dt>烟油容量 / E-liquid</dt><dd>{snapshot.policy.maxELiquidMl} ml</dd></div><div><dt>记录日期 / Record date</dt><dd>{snapshot.policy.recordAt}</dd></div></dl></div><div className="print-section"><h2>贸易快照 / Trade snapshot</h2>{snapshot.trade.map((point) => <div className="print-trade" key={point.year}><span>{point.year}</span><i><b style={{width:`${Math.min(100,point.valueUsdM/Math.max(...snapshot.trade.map(x=>x.valueUsdM))*100)}%`}}/></i><strong>${point.valueUsdM}M</strong></div>)}<small>HS 85434000 · 数据更新至 / Data current to 2024-07</small></div></section>
    <section className="print-columns insight"><div className="print-section"><h2>主要机会 / Opportunities</h2>{evaluation.opportunitiesZh.map((item,index)=><p key={item}>• {item}<br/><small>{evaluation.opportunitiesEn[index]}</small></p>)}</div><div className="print-section"><h2>主要风险 / Risks</h2>{evaluation.risksZh.map((item,index)=><p key={item}>• {item}<br/><small>{evaluation.risksEn[index]}</small></p>)}</div></section>
    <section className="print-section page-break"><h2>相似产品对标 / Comparable products</h2><table><thead><tr><th>产品 / Product</th><th>口数 / Puffs</th><th>容量 / Volume</th><th>零售价 / Retail</th><th>特征 / Attributes</th></tr></thead><tbody>{snapshot.competitors.slice(0,4).map((item)=><tr key={item.id}><td><strong>{item.brand} {item.name}</strong></td><td>{item.puffs.toLocaleString()}</td><td>{item.eLiquidMl} ml</td><td>${item.retailPriceUsd}</td><td>{item.features.slice(0,2).join(", ")}</td></tr>)}</tbody></table></section>
    <section className="print-section"><h2>证据清单 / Evidence register</h2><table><thead><tr><th>证据 / Evidence</th><th>来源 / Source</th><th>日期 / Date</th><th>质量 / Quality</th><th>采用 / Used</th></tr></thead><tbody>{evaluation.evidence.map((item)=><tr key={item.id}><td><strong>{item.titleZh}</strong><small>{item.titleEn}</small></td><td>{item.source}</td><td>{item.recordAt}</td><td>{item.quality}</td><td>{item.usedInScore?"YES":"NO"}</td></tr>)}</tbody></table><div className="print-warnings"><h3>数据质量警告 / Data quality warnings</h3>{evaluation.dataWarningsZh.map((item,index)=><p key={item}>• {item}<br/><small>{evaluation.dataWarningsEn[index]}</small></p>)}</div></section>
    <footer className="print-footer"><span>{evaluation.id}</span><span>{evaluation.dataVersion}</span><span>{evaluation.scoringVersion}</span><span>{new Date(evaluation.createdAt).toLocaleDateString()}</span></footer>
  </main>;
}
